SpawnRate 4
WifeSpawn 2
LockNLoad 1
GunSpawnRate 2
WepSpawnRate 2
HostileSpawnRate 1
MaxHostileSpawnRate 17
InfinitAmmo 1
FindWork 1
SurvivorFriendliness 4
RaidersAtLeastHours 13
RaidersAfterHours 7
RaidersChance 3
Bravery 2
SSHotkey1 6
SSHotkey2 17
SSHotkey3 27
SSHotkey4 42
SurvivorHunger 1
